// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtWVjyK4m8vKe2c0RKWUIuuXX4Mauqjag',
    appId: '1:623404480415:web:c6f7b34492c0a006fbafaa',
    messagingSenderId: '623404480415',
    projectId: 'keep-clone-e5b0b',
    authDomain: 'keep-clone-e5b0b.firebaseapp.com',
    storageBucket: 'keep-clone-e5b0b.firebasestorage.app',
    measurementId: 'G-R93CNXMR55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqptcawxdOaciF1qAXx3RqXATFcm1Tq4Q',
    appId: '1:623404480415:android:33d3a98a3ceb5ab0fbafaa',
    messagingSenderId: '623404480415',
    projectId: 'keep-clone-e5b0b',
    storageBucket: 'keep-clone-e5b0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARX35AgCb3euDCmGyCwECrtD5T7WZUCbU',
    appId: '1:623404480415:ios:af8a3e3c3b3f9da8fbafaa',
    messagingSenderId: '623404480415',
    projectId: 'keep-clone-e5b0b',
    storageBucket: 'keep-clone-e5b0b.firebasestorage.app',
    iosBundleId: 'com.example.googleKeepClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARX35AgCb3euDCmGyCwECrtD5T7WZUCbU',
    appId: '1:623404480415:ios:af8a3e3c3b3f9da8fbafaa',
    messagingSenderId: '623404480415',
    projectId: 'keep-clone-e5b0b',
    storageBucket: 'keep-clone-e5b0b.firebasestorage.app',
    iosBundleId: 'com.example.googleKeepClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBtWVjyK4m8vKe2c0RKWUIuuXX4Mauqjag',
    appId: '1:623404480415:web:cca5430e5ca722a7fbafaa',
    messagingSenderId: '623404480415',
    projectId: 'keep-clone-e5b0b',
    authDomain: 'keep-clone-e5b0b.firebaseapp.com',
    storageBucket: 'keep-clone-e5b0b.firebasestorage.app',
    measurementId: 'G-JXT5CCHSSH',
  );

}